{% set version = '0.1.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-support
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/support_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/support/support_{{ version }}.tar.gz
  sha256: 46e8ae5b5cba96339314fc49ebf182eea39f12bfbfde01678a93d52e1ec79b3f

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-bh
    - r-mhadaptive
    - r-rcpp >=0.12.4
    - r-rcpparmadillo
    - r-doparallel
    - r-matrixstats
    - r-nloptr
    - r-randtoolbox
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-bh
    - r-mhadaptive
    - r-rcpp >=0.12.4
    - r-rcpparmadillo
    - r-doparallel
    - r-matrixstats
    - r-nloptr
    - r-randtoolbox

test:
  commands:
    - $R -e "library('support')"           # [not win]
    - "\"%R%\" -e \"library('support')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=support
  license: GPL (>= 2)
  summary: The 'support' package provides the functions sp() and sp_seq() for computing the support
    points in Mak and Joseph (2018) <DOI:10.1214/17-AOS1629>. Support points can be
    used as a representative sample of a desired distribution, or a representative reduction
    of a big dataset (e.g., an "optimal" thinning of Markov-chain Monte Carlo sample
    chains). This work was supported by USARO grant W911NF-14-1-0024 and NSF DMS grant
    1712642.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: support
# Type: Package
# Title: Support Points
# Version: 0.1.3
# Author: Simon Mak
# Maintainer: Simon Mak <smak6@gatech.edu>
# Description: The 'support' package provides the functions sp() and sp_seq() for computing the support points in Mak and Joseph (2018) <DOI:10.1214/17-AOS1629>. Support points can be used as a representative sample of a desired distribution, or a representative reduction of a big dataset (e.g., an "optimal" thinning of Markov-chain Monte Carlo sample chains). This work was supported by USARO grant W911NF-14-1-0024 and NSF DMS grant 1712642.
# License: GPL (>= 2)
# LazyData: TRUE
# Imports: Rcpp (>= 0.12.4), randtoolbox, matrixStats, doParallel, nloptr, MHadaptive
# LinkingTo: Rcpp, RcppArmadillo, BH
# RoxygenNote: 6.0.1
# NeedsCompilation: yes
# Packaged: 2019-05-23 19:11:09 UTC; smak6
# Repository: CRAN
# Date/Publication: 2019-05-23 19:30:03 UTC
