# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxxtarget_platformosx-64
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxxtarget_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "lCdvCjKvMOZFtAK0DhrDJIbAqG6kznuK0E/oDEGc/Ft8QCyrgIJ7GMGKPIuHPcIVXBWAWOR7KYzKS2VEpZX+ACXiQnE+Qd82Gz9Ue+YKhSjamXfgsQTTDdNuCZBHFCZuxAC8TF9+cOe5FnDmX+hM9Jr1WQyeSiCtPEpJxK0+mOtFm05s6Vu1X+5q+m6YTAj0IoXI9QOTfGQkJRdTCODX771iXgP6bUrenJI5T8BETwm4MdBz+9YWQM0PiT8mdyf4EyWSwp0Ic0xPWHNSsO/lrcz1VzRoOJ9yvwggGLQcj/lnEmtWC7mFDbEY+NmRAFXG2Wsq34oK/mEVa+2riHcGPuJYCk4UsBNH+UnteWSR4yn1S0Youvpfk+tVh9C6aeypDftSG8i+lVwDz57+aY3g1ROMsoVW0H6HHXGpqbXQ014bd07V4fsq44ALTy7SUo8yJNROooB/o8FwLbNbFCA+cMKXwwnxRI0WwJWFZ2EjMMIKw2viCiQtCcGMA3oxv4f6To0rMWTQwPC24LUcZibVDkK/O/LiouRQkmu2LvM0Hoqk23daNE1V1ys569XiOeKGfcqv8pEZAnPtY0sLJZXqQCWtJ79yS6+LR93Ex+XeSs2A17aEQAhjJvOj8Z2Bp9s0pd1Rh4MBRErrZXJg6JnT3Sdne5K4V7JOdoTECOsmyxY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
