appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: lCdvCjKvMOZFtAK0DhrDJIbAqG6kznuK0E/oDEGc/Ft8QCyrgIJ7GMGKPIuHPcIVXBWAWOR7KYzKS2VEpZX+ACXiQnE+Qd82Gz9Ue+YKhSjamXfgsQTTDdNuCZBHFCZuxAC8TF9+cOe5FnDmX+hM9Jr1WQyeSiCtPEpJxK0+mOtFm05s6Vu1X+5q+m6YTAj0IoXI9QOTfGQkJRdTCODX771iXgP6bUrenJI5T8BETwm4MdBz+9YWQM0PiT8mdyf4EyWSwp0Ic0xPWHNSsO/lrcz1VzRoOJ9yvwggGLQcj/lnEmtWC7mFDbEY+NmRAFXG2Wsq34oK/mEVa+2riHcGPuJYCk4UsBNH+UnteWSR4yn1S0Youvpfk+tVh9C6aeypDftSG8i+lVwDz57+aY3g1ROMsoVW0H6HHXGpqbXQ014bd07V4fsq44ALTy7SUo8yJNROooB/o8FwLbNbFCA+cMKXwwnxRI0WwJWFZ2EjMMIKw2viCiQtCcGMA3oxv4f6To0rMWTQwPC24LUcZibVDkK/O/LiouRQkmu2LvM0Hoqk23daNE1V1ys569XiOeKGfcqv8pEZAnPtY0sLJZXqQCWtJ79yS6+LR93Ex+XeSs2A17aEQAhjJvOj8Z2Bp9s0pd1Rh4MBRErrZXJg6JnT3Sdne5K4V7JOdoTECOsmyxY=
conda_forge_output_validation: false
